{"name": "src.utils.snk_requester", "timestamp": "2025-04-25T17:19:25Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 863248, "message": "Erro no servi\u00e7o DatasetSP.loadRecords: status=3, message=N\u00e3o autorizado."}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T11:47:41Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 2865249, "message": "Erro no servi\u00e7o DatasetSP.loadRecords: status=3, message=N\u00e3o autorizado."}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T14:59:32Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 1999548, "message": "Erro no servi\u00e7o DatasetSP.loadRecords: status=3, message=N\u00e3o autorizado."}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T15:00:58Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 2019706, "message": "Erro no servi\u00e7o ImportacaoXMLNotasSP.validarImportacao: status=0, message=J\u00e1 existe um CT-e na Central com essa chave de acesso.\nNro. \u00danico Nota: 168796\nEmpresa: 2\nChave de Acesso: 35250487183570000223570010026092841136528170"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T15:25:33Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 2434846, "message": "Erro no servi\u00e7o DatasetSP.loadRecords: status=3, message=N\u00e3o autorizado."}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T15:26:09Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 2442588, "message": "Erro no servi\u00e7o ActionButtonsSP.executeScript: status=0, message=<b>Regra Personalizada:</b><br>ORA-00936: express\u00e3o n\u00e3o encontrada\n\nLinha do Script: 2"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T15:26:10Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 2442588, "message": "Erro no servi\u00e7o ImportacaoXMLNotasSP.validarImportacao: status=0, message=J\u00e1 existe um CT-e na Central com essa chave de acesso.\nNro. \u00danico Nota: 168851\nEmpresa: 2\nChave de Acesso: 35250487183570000223570010026082341136517423"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T15:26:11Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 2442588, "message": "Erro no servi\u00e7o ImportacaoXMLNotasSP.validarImportacao: status=0, message=J\u00e1 existe um CT-e na Central com essa chave de acesso.\nNro. \u00danico Nota: 168852\nEmpresa: 2\nChave de Acesso: 35250487183570000223570010026092751136527868"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T15:26:11Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 2442588, "message": "Erro no servi\u00e7o ImportacaoXMLNotasSP.validarImportacao: status=0, message=J\u00e1 existe um CT-e na Central com essa chave de acesso.\nNro. \u00danico Nota: 168796\nEmpresa: 2\nChave de Acesso: 35250487183570000223570010026092841136528170"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T15:26:11Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 2442588, "message": "Erro no servi\u00e7o ImportacaoXMLNotasSP.validarImportacao: status=0, message=J\u00e1 existe um CT-e na Central com essa chave de acesso.\nNro. \u00danico Nota: 168853\nEmpresa: 2\nChave de Acesso: 43250487183570000142570010005574201110962910"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T15:32:31Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 2548848, "message": "Erro no servi\u00e7o ActionButtonsSP.executeScript: status=0, message=<b>Regra Personalizada:</b><br>ORA-00936: express\u00e3o n\u00e3o encontrada\n\nLinha do Script: 2"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T15:32:32Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 2548848, "message": "Erro no servi\u00e7o ImportacaoXMLNotasSP.validarImportacao: status=0, message=J\u00e1 existe um CT-e na Central com essa chave de acesso.\nNro. \u00danico Nota: 168851\nEmpresa: 2\nChave de Acesso: 35250487183570000223570010026082341136517423"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T15:32:32Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 2548848, "message": "Erro no servi\u00e7o ImportacaoXMLNotasSP.validarImportacao: status=0, message=J\u00e1 existe um CT-e na Central com essa chave de acesso.\nNro. \u00danico Nota: 168852\nEmpresa: 2\nChave de Acesso: 35250487183570000223570010026092751136527868"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T15:32:33Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 2548848, "message": "Erro no servi\u00e7o ImportacaoXMLNotasSP.validarImportacao: status=0, message=J\u00e1 existe um CT-e na Central com essa chave de acesso.\nNro. \u00danico Nota: 168796\nEmpresa: 2\nChave de Acesso: 35250487183570000223570010026092841136528170"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T15:32:33Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 2548848, "message": "Erro no servi\u00e7o ImportacaoXMLNotasSP.validarImportacao: status=0, message=J\u00e1 existe um CT-e na Central com essa chave de acesso.\nNro. \u00danico Nota: 168853\nEmpresa: 2\nChave de Acesso: 43250487183570000142570010005574201110962910"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T15:33:49Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 2569360, "message": "Erro no servi\u00e7o ActionButtonsSP.executeScript: status=0, message=<b>Regra Personalizada:</b><br>ORA-00936: express\u00e3o n\u00e3o encontrada\n\nLinha do Script: 2"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T15:33:50Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 2569360, "message": "Erro no servi\u00e7o ImportacaoXMLNotasSP.validarImportacao: status=0, message=J\u00e1 existe um CT-e na Central com essa chave de acesso.\nNro. \u00danico Nota: 168851\nEmpresa: 2\nChave de Acesso: 35250487183570000223570010026082341136517423"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T15:33:51Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 2569360, "message": "Erro no servi\u00e7o ImportacaoXMLNotasSP.validarImportacao: status=0, message=J\u00e1 existe um CT-e na Central com essa chave de acesso.\nNro. \u00danico Nota: 168852\nEmpresa: 2\nChave de Acesso: 35250487183570000223570010026092751136527868"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T15:33:51Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 2569360, "message": "Erro no servi\u00e7o ImportacaoXMLNotasSP.validarImportacao: status=0, message=J\u00e1 existe um CT-e na Central com essa chave de acesso.\nNro. \u00danico Nota: 168796\nEmpresa: 2\nChave de Acesso: 35250487183570000223570010026092841136528170"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T15:33:51Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 2569360, "message": "Erro no servi\u00e7o ImportacaoXMLNotasSP.validarImportacao: status=0, message=J\u00e1 existe um CT-e na Central com essa chave de acesso.\nNro. \u00danico Nota: 168853\nEmpresa: 2\nChave de Acesso: 43250487183570000142570010005574201110962910"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T16:53:48Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 3840905, "message": "Erro no servi\u00e7o DatasetSP.loadRecords: status=3, message=N\u00e3o autorizado."}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T16:54:43Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 3850660, "message": "Erro no servi\u00e7o ActionButtonsSP.executeScript: status=0, message=<b>Regra Personalizada:</b><br>ORA-00936: express\u00e3o n\u00e3o encontrada\n\nLinha do Script: 2"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T16:54:43Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 3850660, "message": "Erro no servi\u00e7o DatasetSP.loadRecords: status=0, message=Erro ao carregar p\u00e1gina de dados 1 para ImportacaoXMLNotas.\nORA-00907: par\u00eantese direito n\u00e3o encontrado"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T17:19:06Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 4182819, "message": "Erro no servi\u00e7o DatasetSP.loadRecords: status=0, message=Erro ao carregar p\u00e1gina de dados 1 para ImportacaoXMLNotas.\nORA-00907: par\u00eantese direito n\u00e3o encontrado"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T17:20:38Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 11301, "message": "Erro no servi\u00e7o ActionButtonsSP.executeScript: status=0, message=<b>Regra Personalizada:</b><br>ORA-00936: express\u00e3o n\u00e3o encontrada\n\nLinha do Script: 2"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T17:20:40Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 11301, "message": "Erro no servi\u00e7o ImportacaoXMLNotasSP.validarImportacao: status=0, message=Elemento de um EntityPrimaryKey n\u00e3o pode ser nulo"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T17:20:40Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 11301, "message": "Erro no servi\u00e7o ImportacaoXMLNotasSP.validarImportacao: status=0, message=Elemento de um EntityPrimaryKey n\u00e3o pode ser nulo"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T17:20:40Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 11301, "message": "Erro no servi\u00e7o ImportacaoXMLNotasSP.validarImportacao: status=0, message=Elemento de um EntityPrimaryKey n\u00e3o pode ser nulo"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T17:20:40Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 11301, "message": "Erro no servi\u00e7o ImportacaoXMLNotasSP.validarImportacao: status=0, message=Elemento de um EntityPrimaryKey n\u00e3o pode ser nulo"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T17:35:50Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 217991, "message": "Erro no servi\u00e7o DatasetSP.loadRecords: status=0, message=Erro ao carregar p\u00e1gina de dados 1 para ImportacaoXMLNotas.\nORA-00907: par\u00eantese direito n\u00e3o encontrado"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T17:53:04Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 462229, "message": "Erro no servi\u00e7o ActionButtonsSP.executeScript: status=0, message=<b>Regra Personalizada:</b><br>ORA-00936: express\u00e3o n\u00e3o encontrada\n\nLinha do Script: 2"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T17:53:05Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 462229, "message": "Erro no servi\u00e7o DatasetSP.loadRecords: status=0, message=Erro ao carregar p\u00e1gina de dados 1 para ImportacaoXMLNotas.\nORA-00907: par\u00eantese direito n\u00e3o encontrado"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-28T17:55:14Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 493463, "message": "Erro no servi\u00e7o ActionButtonsSP.executeScript: status=0, message=<b>Regra Personalizada:</b><br>ORA-00936: express\u00e3o n\u00e3o encontrada\n\nLinha do Script: 2"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-29T11:05:40Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 2040275, "message": "Erro no servi\u00e7o ActionButtonsSP.executeScript: status=0, message=<b>Regra Personalizada:</b><br>ORA-00936: express\u00e3o n\u00e3o encontrada\n\nLinha do Script: 2"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-29T11:14:51Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 2172461, "message": "Erro no servi\u00e7o ActionButtonsSP.executeScript: status=0, message=<b>Regra Personalizada:</b><br>ORA-00936: express\u00e3o n\u00e3o encontrada\n\nLinha do Script: 2"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-29T11:31:15Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 2409386, "message": "Erro no servi\u00e7o ActionButtonsSP.executeScript: status=0, message=<b>Regra Personalizada:</b><br>ORA-00936: express\u00e3o n\u00e3o encontrada\n\nLinha do Script: 2"}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-29T14:27:07Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 807524, "message": "Erro no servi\u00e7o DatasetSP.loadRecords: status=3, message=N\u00e3o autorizado."}
{"name": "src.utils.snk_requester", "timestamp": "2025-04-29T14:48:20Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 1112304, "message": "Erro no servi\u00e7o ActionButtonsSP.executeScript: status=0, message=<b>Regra Personalizada:</b><br>ORA-00936: express\u00e3o n\u00e3o encontrada\n\nLinha do Script: 2"}
{"name": "utils.snk_requester", "timestamp": "2025-04-30T08:59:49Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 461555, "message": "Erro no servi\u00e7o DatasetSP.loadRecords: status=3, message=N\u00e3o autorizado."}
